### ISSUE TITLE
Joomla plugin update error

### ISSUE THREAD

**Issue by crazy4groovy** [jmosmap/plugin_googlemaps#10]
Error

Package download failed: https://github.com/jmosmap/plugin_googlemaps/releases/download/J25_J3x.v3.3/plugin_googlemaps-J25_J3x.v3.3.zip

**Comment by crazy4groovy** [comment]
Warning
Error connecting to the server: SSL certificate problem: unable to get local issuer certificate

**Comment by jmosmap** [comment]
You can get an error when automatically updating: Error connecting to the server: SSL certificate problem: unable to get local issuer certificate Error.

This problem cannot be solved by the plugin. The files are at Github (a large website for projects). The SSL certificate problem can be caused by webservers that do not have all the list with all the certificate providers up to date, see: https://help.github.com/articles/error-ssl-certificate-problem-verify-that-the-ca-cert-is-ok/

You can download the file and install it manually.

**Comment by jmosmap** [comment]
Added a download location without https.

Crazy4groovy, can you test it?

**Comment by jmosmap** [comment]
Any news

**Comment by jmosmap** [comment]
Number of emails on problem with updating lowered to zero last week so solution seems to work
