### ISSUE TITLE
Warning at Joomla Control Panel - Extension Update

### ISSUE THREAD

**Issue by gomopa** [jmosmap/plugin_googlemaps#23]
Getting always this warning:
Update: Could not open update site #9 "Plugin Googlemap Update Site", URL: http://tech.reumer.net/update/plugin_googlemap3/extension.xml

Is there any solution to avoid this
Thanks Go

**Comment by jmosmap** [comment]
I switch off the upgrade possibility due to high load on my update server.
When a new version will be launched it will be active again.

I am discussing a solution with my hosting provider

**Comment by Chacapamac** [comment]
Same Here - Update is not connecting

**Comment by jmosmap** [comment]
I switch off the upgrade possibility due to high load on my update server.
When a new version will be launched it will be active again.

I am discussing a solution with my hosting provider.

The problem is that all users refer to the file on my webserver and I can only change it with an update of the plugin. I hope this will be soon.

You can change the url in your database, table _updates_site and search for "Plugin Googlemap" and use the following url: https://raw.githubusercontent.com/jmosmap/plugin_googlemaps/master/update/extension.xml

**Comment by jmosmap** [comment]
In version 3.4 the update server url is updated by the plugin itself. Joomla has a bug and does not update the url but adds a second update site in the list instead.
